name = "alisa-cake-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "alisa-cake-db"
database_id = "67fe7730-a692-4b1b-a9a3-2486daf0b57c"

# R2 存储桶绑定 (用于图片存储)
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "image"

# 生产环境变量
[env.production]
vars = { ENVIRONMENT = "production" }
